name: Publish Jupyter Book

on:
  push:
    branches:
      # NOTE: You may want to limit the trigger branch to be "main" or "master" etc.
      - '*'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4


      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: _build/html/
          target-branch: gh-pages
