name: Publish Jupyter Book

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Jupyter Book
        run: pip install jupyter-book

      - name: Build the book
        run: jupyter-book build .

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: _build/html/
          target-branch: gh-pages
